### ISSUE TITLE
poisson_limits in IDL breaks for 0 or 1 events

### ISSUE THREAD

**Issue by nathaniel** [hainest/SmallNumberStatistics#3]
In the IDL part of the library (haven't checked the others):

Trying to get poisson confidence intervals for the case of 0 or 1 recorded events causes an error. In both cases, k=0 gets passed to pdtri.pro, which proceeds to use 1./k as part of the process of finding the x0 initial guess to bass to the bisection routine. This yields x0 = NaN which then gets passed to igamma(), causing the error.

My local solution is to simply add a conditional in pdtri.pro, such that if k=0, then x0 gets set to 0. But perhaps there is a better way?

Thanks,
Nathaniel

**Comment by hainest** [comment]
pdtri(0, cl) should return something larger than zero for the upper limit (the lower limit is zero by convention). The Python and Perl versions handle this automatically as they use the Cephes library directly. Let me check what they do, and we'll change the IDL version to do the same. Thanks!

**Comment by hainest** [comment]
The problem was that I had the k+1 on the wrong side of the call to igami. Simple fix and added tests to confirm. Thanks for the bug report!
